version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - s3server-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
      - REDIS_DB=0
      - REDIS_PREFIX=s3server:
      - DB_PATH=/var/www/html/storage/database.sqlite
    depends_on:
      - redis
    networks:
      - s3server-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_redis_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - s3server-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-your_redis_password}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - s3server-network

networks:
  s3server-network:
    driver: bridge

volumes:
  redis_data:
